### ISSUE TITLE
Language switching bug

### ISSUE THREAD

**Issue by iawen** [Unstructured-IO/unstructured-inference#93]
Hello, inferenceelements.py, when calling the aggregate_by_block function, the ocr_languages is not passed, resulting in invalid switching language
```py
# text = aggregate_by_block(self, image, objects, ocr_strategy)
text = aggregate_by_block(self, image, objects, ocr_strategy, languages=ocr_languages)
```

**Comment by qued** [comment]
A lot has changed since this issue was opened. OCR is now almost all handled in the `unstructured` library rather than here, and `aggregate_by_block` no longer has an OCR call. I added a test in `unstructured` to ensure languages are getting passed all the way to the OCR call, and since it is passing with no other changes, I think this issue has been closed in the meantime.
